package com.np.order.models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.Table;

/*
 * 加盟店マスタ Model
 *
 * This class was autogenerated on:
 * [Mon Jan 11 18:47:34 JST 2016]
 *
 * [WARNING]
 * Don't edit this class directly, because it may be regenerated late.
 */
@Entity
@Table(name = "NAPA_TERMINAL_TBL")
public class NapaTerminal {
	public static final String TABLE_NAME = "NAPA_TERMINAL_TBL";

	/*
	 * ---------------------- Public Field Names Definition
	 * ----------------------------
	 */
	public static final String NAPAId = "NapaId";
	public static final String USERID = "TerminalID";
	public static final String USERNAME = "TerminalKind";
	public static final String PASSWORD = "TerminalIP";

	/*
	 * ---------------------- Private Fields Definition
	 * ----------------------------
	 */
	@Id
	/* 加盟店ID */
	@Column(name = "NAPAId", length = 64, nullable = false)
	private String NapaId;

	/* 端末ID  */
	@Column(name = "TerminalID", length = 64, nullable = true)
	private String TerminalID;

	/* 端末分野 */
	@Column(name = "TerminalKind", length = 64, nullable = true)
	private String TerminalKind;

	/* 端末IP  */
	@Column(name = "TerminalIP", length = 64, nullable = true)
	private String TerminalIP;


	public static String getTableName() {
		return TABLE_NAME;
	}

	public String getNapaId() {
		return NapaId;
	}

	public void setNapaId(String napaId) {
		NapaId = napaId;
	}

	public String getTerminalID() {
		return TerminalID;
	}

	public void setTerminalID(String terminalID) {
		TerminalID = terminalID;
	}

	public String getTerminalKind() {
		return TerminalKind;
	}

	public void setTerminalKind(String terminalKind) {
		TerminalKind = terminalKind;
	}

	public String getTerminalIP() {
		return TerminalIP;
	}

	public void setTerminalIP(String terminalIP) {
		TerminalIP = terminalIP;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("\t");
		sb.append("TerminalID");
		sb.append("=");
		sb.append(TerminalID);
		sb.append("\n");
		sb.append("\t");
		sb.append("NapaId");
		sb.append("=");
		sb.append(NapaId);
		sb.append("\n");
		sb.append("\t");
		sb.append("TerminalKind");
		sb.append("=");
		sb.append(TerminalKind);
		sb.append("\n");
		sb.append("\t");
		sb.append("TerminalIP");
		sb.append("=");
		sb.append(TerminalIP);
		sb.append("\n");
		return sb.toString();
	}


}
